APP_NAME: "WebCrawler"
TIME_FORMAT: "02-Jan-2006"
TIME_ZONE: "America/Sao_Paulo"
MAX_CONCURRENCY: 10
MAX_DEPTH: 2
POSTGRES_URI: "postgres://postgres:Strong@P4ssword@localhost/crawler"
URL: "https://www.uol.com.br"
CACHE:
  DB_DIR: "/tmp/WebCrawler"
  MODE: "disc"  # "mem" para memória, "disc" para disco
PROXY:
  ENABLED: false
  PROXY_URL: "http://localhost:4444"
FILTER:
  TLDS: []  # Lista de TLDs, exemplo: [com, br, org]
